---
# This role installs httpd

- name: Install http and php etc
  apt: name={{ item }} update_cache=yes state=present
  with_items:
   - apache2

- name: http service state
  service: name=apache2 state=started enabled=yes

#- name: Configure the Index.html file with IP Address
#  template: src=index.html.j2 dest=/var/www/html/index.html backup=yes
#  when: 
#  notify: restart apache2
