---
# This role contains common plays that will run on all nodes.

- name: Uninstall php and git 
  apt: name={{ item }} state=absent
  with_items:
   - ntp
   - apache2
   - php
   - php-mysql
   - git
   - haproxy
   - socat